"""empty message

Revision ID: 042229a36cc1
Revises: 402670e5083b
Create Date: 2022-01-22 15:12:15.996416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042229a36cc1'
down_revision = '402670e5083b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('month')

    # ### end Alembic commands ###
