"""empty message

Revision ID: 88c1b3291044
Revises: 7ca83cf86add
Create Date: 2022-02-03 20:41:28.516447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c1b3291044'
down_revision = '7ca83cf86add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notiflist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notiflist')
    # ### end Alembic commands ###
