"""'function_test'

Revision ID: 8daf01f02faf
Revises: 91652a53c850
Create Date: 2022-01-13 14:12:46.635071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8daf01f02faf'
down_revision = '91652a53c850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('expense_status',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('cost_description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('cost',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cost_description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('expense_status',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)

    # ### end Alembic commands ###
