"""'status_add'

Revision ID: 91652a53c850
Revises: fad0fc4c20b2
Create Date: 2021-12-27 10:47:20.655089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91652a53c850'
down_revision = 'fad0fc4c20b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('T_Number', sa.String(length=10), nullable=False),
    sa.Column('repair_id', sa.String(length=10), nullable=False),
    sa.Column('expense_status', sa.String(length=5), nullable=True),
    sa.Column('cost_description', sa.Text(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['T_Number'], ['status.T_Number'], ),
    sa.ForeignKeyConstraint(['repair_id'], ['status.repair_id'], ),
    sa.PrimaryKeyConstraint('T_Number', 'repair_id')
    )
    op.add_column('status', sa.Column('T_Number', sa.String(length=10), nullable=False))
    op.add_column('status', sa.Column('active_notes', sa.Text(), nullable=True))
    op.drop_constraint(None, 'status', type_='foreignkey')
    op.create_foreign_key(None, 'status', 'vehicle', ['T_Number'], ['T_Number'])
    op.drop_column('status', 'parts_needed')
    op.drop_column('status', 'region')
    op.drop_column('status', 'active_reason')
    op.drop_column('status', 'T_num')
    op.drop_column('status', 'estimated_repair_cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('estimated_repair_cost', sa.INTEGER(), nullable=True))
    op.add_column('status', sa.Column('T_num', sa.VARCHAR(length=10), nullable=False))
    op.add_column('status', sa.Column('active_reason', sa.TEXT(), nullable=True))
    op.add_column('status', sa.Column('region', sa.VARCHAR(length=64), nullable=True))
    op.add_column('status', sa.Column('parts_needed', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'status', type_='foreignkey')
    op.create_foreign_key(None, 'status', 'vehicle', ['T_num'], ['T_Number'])
    op.drop_column('status', 'active_notes')
    op.drop_column('status', 'T_Number')
    op.drop_table('expense')
    # ### end Alembic commands ###
