"""empty message

Revision ID: a2b8d09a533c
Revises: 8daf01f02faf
Create Date: 2022-01-21 11:07:15.198959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b8d09a533c'
down_revision = '8daf01f02faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    None

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    None
    # ### end Alembic commands ###
