"""'test2'

Revision ID: c23e338bc690
Revises: 09206d505eb5
Create Date: 2021-12-23 13:45:19.946113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23e338bc690'
down_revision = '09206d505eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index('ix_vehicle_T_Number', table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_table('service')
    op.drop_index('ix_status_status', table_name='status')
    op.drop_table('status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('T_num', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), nullable=False),
    sa.Column('repair_id', sa.VARCHAR(length=24), nullable=True),
    sa.Column('date_garage', sa.INTEGER(), nullable=True),
    sa.Column('garage_reason', sa.TEXT(), nullable=True),
    sa.Column('estimated_repair_time', sa.VARCHAR(length=64), nullable=True),
    sa.Column('estimated_repair_cost', sa.INTEGER(), nullable=True),
    sa.Column('date_parked', sa.INTEGER(), nullable=True),
    sa.Column('park_reason', sa.TEXT(), nullable=True),
    sa.Column('region', sa.VARCHAR(length=64), nullable=True),
    sa.Column('date_active', sa.INTEGER(), nullable=True),
    sa.Column('active_reason', sa.TEXT(), nullable=True),
    sa.Column('parts_needed', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['T_num'], ['vehicle.T_Number'], ),
    sa.PrimaryKeyConstraint('status')
    )
    op.create_index('ix_status_status', 'status', ['status'], unique=False)
    op.create_table('service',
    sa.Column('T_Number', sa.VARCHAR(length=10), nullable=False),
    sa.Column('odometer', sa.INTEGER(), nullable=True),
    sa.Column('service_date', sa.DATETIME(), nullable=True),
    sa.Column('service_date2', sa.DATETIME(), nullable=True),
    sa.Column('service_date3', sa.DATETIME(), nullable=True),
    sa.Column('service_date5', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['T_Number'], ['vehicle.T_Number'], ),
    sa.PrimaryKeyConstraint('T_Number')
    )
    op.create_table('vehicle',
    sa.Column('T_Number', sa.VARCHAR(length=10), nullable=False),
    sa.Column('white_plate', sa.VARCHAR(length=10), nullable=True),
    sa.Column('green_plate', sa.VARCHAR(length=10), nullable=True),
    sa.Column('department', sa.VARCHAR(length=64), nullable=True),
    sa.Column('ownership_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('owner_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('driver_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('region', sa.VARCHAR(length=64), nullable=True),
    sa.Column('amber', sa.VARCHAR(length=10), nullable=True),
    sa.Column('flow_sticker', sa.VARCHAR(length=10), nullable=True),
    sa.Column('telicon_sticker', sa.VARCHAR(length=10), nullable=True),
    sa.Column('lpg_gas', sa.VARCHAR(length=10), nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=25), nullable=True),
    sa.Column('car_model', sa.VARCHAR(length=25), nullable=True),
    sa.Column('year', sa.VARCHAR(length=64), nullable=True),
    sa.Column('color', sa.VARCHAR(length=64), nullable=True),
    sa.Column('chasis_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('engine_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('registration_exp', sa.INTEGER(), nullable=True),
    sa.Column('fitness_exp', sa.INTEGER(), nullable=True),
    sa.Column('carrier_exp', sa.INTEGER(), nullable=True),
    sa.Column('cn_exp', sa.INTEGER(), nullable=True),
    sa.Column('insurance_exp', sa.INTEGER(), nullable=True),
    sa.Column('insurance_company', sa.VARCHAR(length=64), nullable=True),
    sa.Column('gas_type', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('T_Number')
    )
    op.create_index('ix_vehicle_T_Number', 'vehicle', ['T_Number'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('pwd', sa.VARCHAR(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('pwd')
    )
    # ### end Alembic commands ###
