"""empty message

Revision ID: dc8fb4607b5f
Revises: 88c1b3291044
Create Date: 2022-02-07 10:43:45.844806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8fb4607b5f'
down_revision = '88c1b3291044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notiflist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notiflist', schema=None) as batch_op:
        batch_op.drop_column('read')

    # ### end Alembic commands ###
