"""empty message

Revision ID: f30bd35b2e1f
Revises: dc8fb4607b5f
Create Date: 2022-02-08 11:26:51.675002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30bd35b2e1f'
down_revision = 'dc8fb4607b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('T_Number', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('date_garage', sa.Date(), nullable=True),
    sa.Column('garage_reason', sa.Text(), nullable=True),
    sa.Column('repair_id', sa.String(length=24), nullable=True),
    sa.Column('estimated_repair_time', sa.Date(), nullable=True),
    sa.Column('date_parked', sa.Date(), nullable=True),
    sa.Column('park_reason', sa.Text(), nullable=True),
    sa.Column('date_active', sa.Date(), nullable=True),
    sa.Column('active_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['T_Number'], ['vehicle.T_Number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_status'))

    op.drop_table('history')
    # ### end Alembic commands ###
