"""'test3'

Revision ID: fad0fc4c20b2
Revises: c23e338bc690
Create Date: 2021-12-23 18:51:17.004916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad0fc4c20b2'
down_revision = 'c23e338bc690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('pwd', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('pwd')
    )
    op.create_table('vehicle',
    sa.Column('T_Number', sa.String(length=10), nullable=False),
    sa.Column('white_plate', sa.String(length=10), nullable=True),
    sa.Column('green_plate', sa.String(length=10), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('ownership_type', sa.String(length=64), nullable=True),
    sa.Column('owner_name', sa.String(length=64), nullable=True),
    sa.Column('driver_name', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('amber', sa.String(length=10), nullable=True),
    sa.Column('flow_sticker', sa.String(length=10), nullable=True),
    sa.Column('telicon_sticker', sa.String(length=10), nullable=True),
    sa.Column('lpg_gas', sa.String(length=10), nullable=True),
    sa.Column('manufacturer', sa.String(length=25), nullable=True),
    sa.Column('car_model', sa.String(length=25), nullable=True),
    sa.Column('year', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('chasis_number', sa.String(length=64), nullable=True),
    sa.Column('engine_number', sa.String(length=64), nullable=True),
    sa.Column('registration_exp', sa.Integer(), nullable=True),
    sa.Column('fitness_exp', sa.DateTime(), nullable=True),
    sa.Column('carrier_exp', sa.DateTime(), nullable=True),
    sa.Column('cn_exp', sa.DateTime(), nullable=True),
    sa.Column('insurance_exp', sa.DateTime(), nullable=True),
    sa.Column('insurance_company', sa.String(length=64), nullable=True),
    sa.Column('gas_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('T_Number')
    )
    op.create_index(op.f('ix_vehicle_T_Number'), 'vehicle', ['T_Number'], unique=False)
    op.create_table('service',
    sa.Column('T_Number', sa.String(length=10), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=True),
    sa.Column('service_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['T_Number'], ['vehicle.T_Number'], ),
    sa.PrimaryKeyConstraint('T_Number')
    )
    op.create_table('status',
    sa.Column('T_num', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('repair_id', sa.String(length=24), nullable=True),
    sa.Column('date_garage', sa.DateTime(), nullable=True),
    sa.Column('garage_reason', sa.Text(), nullable=True),
    sa.Column('estimated_repair_time', sa.DateTime(), nullable=True),
    sa.Column('estimated_repair_cost', sa.Integer(), nullable=True),
    sa.Column('date_parked', sa.DateTime(), nullable=True),
    sa.Column('park_reason', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('date_active', sa.DateTime(), nullable=True),
    sa.Column('active_reason', sa.Text(), nullable=True),
    sa.Column('parts_needed', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['T_num'], ['vehicle.T_Number'], ),
    sa.PrimaryKeyConstraint('status')
    )
    op.create_index(op.f('ix_status_status'), 'status', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_status'), table_name='status')
    op.drop_table('status')
    op.drop_table('service')
    op.drop_index(op.f('ix_vehicle_T_Number'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_table('user')
    # ### end Alembic commands ###
